export const achievements = [
    {
      id: 1,
      title: 'Historical Scholar',
      description: 'For visiting a number of historical landmarks. Well done :)',
      icon: 'graduation-cap',
      iconType: 'FontAwesome6',
    },
    {
      id: 2,
      title: 'Cultural Enthusiast',
      description: 'For exploring cultural sites such as museums, theaters, or art galleries. Well done :)',
      icon: 'theater-masks',
      iconType: 'FontAwesome5',
    },
    {
      id: 3,
      title: 'Monumental Visitor',
      description: 'For visiting famous monuments and statues. Well done :)',
      icon: 'landmark',
      iconType: 'FontAwesome6',
    },
    {
      id: 4,
      title: 'Trailblazer',
      description: 'For being among the first to visit newly added landmarks or significant places. Well done :)',
      icon: 'flag',
      iconType: 'FontAwesome5',
    },
    {
      id: 5,
      title: 'Local Historian',
      description: 'For learning and sharing information about local historical sites. Well done :)',
      icon: 'search-location',
      iconType: 'FontAwesome5',
    },
    {
      id: 6,
      title: 'Nature Lover',
      description: 'For visiting natural landmarks like national parks, forests, and natural reserves. Well done :)',
      icon: 'tree',
      iconType: 'FontAwesome5',
    },
    {
      id: 7,
      title: 'Architectural Aficionado',
      description: 'For exploring significant architectural landmarks. Well done :)',
      icon: 'building',
      iconType: 'FontAwesome5',
    },
    {
      id: 8,
      title: 'Educational Explorer',
      description: 'For completing educational quests or learning modules about visited places. Well done :)',
      icon: 'lightbulb',
      iconType: 'FontAwesome5',
    },
    {
      id: 9,
      title: 'Event Attender',
      description: 'For attending events at significant places, such as festivals, exhibitions, or historical reenactments. Well done :)',
      icon: 'calendar-alt',
      iconType: 'FontAwesome5',
    },
    {
      id: 10,
      title: 'Photo Master',
      description: 'For taking and uploading photos of significant places. Well done :)',
      icon: 'camera',
      iconType: 'FontAwesome5',
    },
    {
      id: 11,
      title: 'Time Traveler',
      description: 'For visiting sites from different historical periods. Well done :)',
      icon: 'clock',
      iconType: 'FontAwesome5',
    },
  ];
  